server:
  port: 8080

spring:
  profiles:
    active: dev # change to 'prod' when deploying to production
  application:
    name: learn-spring-api
  jpa: # JPA configuration
    hibernate: # Hibernate configuration
      ddl-auto: update # Automatically update the database schema
    show-sql: true # Show SQL queries in the console
    properties: # Hibernate properties
      hibernate: # Hibernate settings
        format_sql: true # Format SQL queries for better readability
        use_sql_comments: true # Use SQL comments in the generated SQL
        type: trace # Enable SQL tracing
        jdbc: # JDBC settings
          lob: # Enable Large Object support
            non_contextual_creation: true # Use non-contextual creation for LOBs

  output: # Output settings
    ansi: # Enable ANSI colors in the console output
      enabled: always # Always enable ANSI colors
    servlet: # Servlet settings
      multipart: # Multipart file upload settings
        max-file-size: 2MB # Maximum file size for uploads -> implement in the future
        max-request-size: 2MB # Maximum request size for uploads -> implement in the future

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    tags-sorter: alpha
    path: /api/v1/docs

logging:
  level:
    root: INFO
    com.giatrong.learning.learnspringapi: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  
  file:
    name: logs/application.log
    max-size: 10MB
    total-size-cap: 100MB
    max-history: 30
    clean-history-on-start: false
